platform :android do
    lane :build do
      gradle(
        task: "assembleRelease",
        build_type: "Release",
        module: "app"
      )
    end
  
    lane :deploy_to_play_store do
      supply(
        track: 'alpha', # ou 'beta', 'production', etc.
        skip_upload_apk: false,
        json_key: ENV["JSON_KEY"]
      )
    end
  end
  