name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Expo CLI
        run: yarn global add expo-cli

      - name: Install Eas CLI
        run: yarn global add @expo/eas-cli

      - name: Install Dependencies
        run: yarn install

      - name: Authenticate with EAS
        run: expo login -u br0wnd3r -p alfatrai619

      - name: Build Expo Project
        run: eas build --platform android # ou yarn expo build:ios

